name: Latest Blog Post Workflow
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write

jobs:
  update-readme-with-latest-blog-posts:
    name: Update README.md With Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch lesterchan.net Blog Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://lesterchan.net/feed"
